In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
data=pd.read_excel("iris_data.xlsx")
a=data.iloc[:,:-1]
data.head()

   slenght  swidth  plength  pwidth           class
0      4.3     2.0      1.4     0.2     Iris-setosa
1      4.4     2.2      1.3     0.2  Iris-virginica
2      4.4     2.2      1.4     0.2  Iris-virginica
3      4.4     2.2      1.5     0.2     Iris-setosa
4      4.5     2.3      1.4     0.2  Iris-virginica

In [51]:
b=data.iloc[:,-1]
b

0         Iris-setosa
1      Iris-virginica
2      Iris-virginica
3         Iris-setosa
4      Iris-virginica
            ...
145       Iris-setosa
146    Iris-virginica
147       Iris-setosa
148       Iris-setosa
149       Iris-setosa
Name: class, Length: 150, dtype: object

In [52]:
model=RandomForestClassifier()
model.fit(a,b)
predition=model.predict([[5.5,3,3.3,1]])
print(predition)

['Iris-versicolor']

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [53]:
dataset=pd.read_excel("iris_test.xlsx")
dataset

    5.5    3  3.3    1  Iris-versicolor
0   6.1  3.1  3.3  1.0   Iris-virginica
1   5.6  3.0  3.5  1.0   Iris-virginica
2   5.8  3.0  3.5  1.0      Iris-setosa
3   5.9  3.0  3.7  1.0  Iris-versicolor
4   5.6  3.0  4.0  1.0  Iris-versicolor
5   5.7  3.0  4.1  1.0      Iris-setosa
6   6.2  3.2  3.0  1.1      Iris-setosa
7   5.9  3.0  3.8  1.1  Iris-versicolor
8   5.7  3.0  3.9  1.1   Iris-virginica
9   5.9  3.0  3.9  1.2  Iris-versicolor
10  6.1  3.1  4.0  1.2  Iris-versicolor
11  6.2  3.2  4.2  1.2      Iris-setosa
12  6.1  3.1  4.4  1.2      Iris-setosa
13  5.8  3.0  4.7  1.2   Iris-virginica
14  5.6  3.0  3.6  1.3  Iris-versicolor
15  5.5  2.9  4.0  1.3      Iris-setosa
16  5.7  3.0  4.0  1.3  Iris-versicolor
17  6.1  3.1  4.0  1.3  Iris-versicolor
18  6.0  3.1  4.1  1.3  Iris-versicolor
19  6.3  3.2  4.1  1.3   Iris-virginica
20  6.1  3.2  4.2  1.3   Iris-virginica
21  6.2  3.2  4.2  1.3  Iris-versicolor
22  5.8  3.0  4.3  1.3      Iris-setosa
23  6.2  3.2  4.3  1.3  Iris-versicolor
24  6.0  3.1  4.4  1.3   Iris-virginica
25  5.5  2.9  4.5  1.3   Iris-virginica
26  5.5  3.0  4.6  1.3  Iris-versicolor
27  5.6  3.0  3.9  1.4      Iris-setosa
28  5.7  3.0  4.4  1.4  Iris-versicolor
29  5.8  3.0  4.4  1.4      Iris-setosa
30  6.1  3.1  4.6  1.4  Iris-versicolor
31  5.4  2.9  4.7  1.4  Iris-versicolor
32  5.6  3.0  4.7  1.4  Iris-versicolor
33  5.8  3.0  4.8  1.4      Iris-setosa
34  6.9  3.6  5.6  1.4      Iris-setosa
35  5.6  3.0  4.2  1.5      Iris-setosa
36  5.4  2.9  4.5  1.5   Iris-virginica
37  5.7  3.0  4.5  1.5  Iris-versicolor
38  5.7  3.0  4.5  1.5  Iris-versicolor
39  5.8  3.0  4.5  1.5   Iris-virginica
40  6.0  3.1  4.5  1.5      Iris-setosa
41  5.5  2.9  4.6  1.5  Iris-versicolor
42  6.0  3.1  4.7  1.5  Iris-versicolor

In [54]:
x_test=dataset.iloc[:,:-1]
x_test

    5.5    3  3.3    1
0   6.1  3.1  3.3  1.0
1   5.6  3.0  3.5  1.0
2   5.8  3.0  3.5  1.0
3   5.9  3.0  3.7  1.0
4   5.6  3.0  4.0  1.0
5   5.7  3.0  4.1  1.0
6   6.2  3.2  3.0  1.1
7   5.9  3.0  3.8  1.1
8   5.7  3.0  3.9  1.1
9   5.9  3.0  3.9  1.2
10  6.1  3.1  4.0  1.2
11  6.2  3.2  4.2  1.2
12  6.1  3.1  4.4  1.2
13  5.8  3.0  4.7  1.2
14  5.6  3.0  3.6  1.3
15  5.5  2.9  4.0  1.3
16  5.7  3.0  4.0  1.3
17  6.1  3.1  4.0  1.3
18  6.0  3.1  4.1  1.3
19  6.3  3.2  4.1  1.3
20  6.1  3.2  4.2  1.3
21  6.2  3.2  4.2  1.3
22  5.8  3.0  4.3  1.3
23  6.2  3.2  4.3  1.3
24  6.0  3.1  4.4  1.3
25  5.5  2.9  4.5  1.3
26  5.5  3.0  4.6  1.3
27  5.6  3.0  3.9  1.4
28  5.7  3.0  4.4  1.4
29  5.8  3.0  4.4  1.4
30  6.1  3.1  4.6  1.4
31  5.4  2.9  4.7  1.4
32  5.6  3.0  4.7  1.4
33  5.8  3.0  4.8  1.4
34  6.9  3.6  5.6  1.4
35  5.6  3.0  4.2  1.5
36  5.4  2.9  4.5  1.5
37  5.7  3.0  4.5  1.5
38  5.7  3.0  4.5  1.5
39  5.8  3.0  4.5  1.5
40  6.0  3.1  4.5  1.5
41  5.5  2.9  4.6  1.5
42  6.0  3.1  4.7  1.5

In [55]:
y_test=dataset.iloc[:,-1]
y_test

0      Iris-virginica
1      Iris-virginica
2         Iris-setosa
3     Iris-versicolor
4     Iris-versicolor
5         Iris-setosa
6         Iris-setosa
7     Iris-versicolor
8      Iris-virginica
9     Iris-versicolor
10    Iris-versicolor
11        Iris-setosa
12        Iris-setosa
13     Iris-virginica
14    Iris-versicolor
15        Iris-setosa
16    Iris-versicolor
17    Iris-versicolor
18    Iris-versicolor
19     Iris-virginica
20     Iris-virginica
21    Iris-versicolor
22        Iris-setosa
23    Iris-versicolor
24     Iris-virginica
25     Iris-virginica
26    Iris-versicolor
27        Iris-setosa
28    Iris-versicolor
29        Iris-setosa
30    Iris-versicolor
31    Iris-versicolor
32    Iris-versicolor
33        Iris-setosa
34        Iris-setosa
35        Iris-setosa
36     Iris-virginica
37    Iris-versicolor
38    Iris-versicolor
39     Iris-virginica
40        Iris-setosa
41    Iris-versicolor
42    Iris-versicolor
Name: Iris-versicolor, dtype: object

In [56]:
predi=model.predict(x_test)
predi

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [57]:
y_test.values

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [46]:
actual=y_test.values

In [58]:
count=0
for i in range(0,len(actual)):
    if actual[i]==predi[i]:
        count=count+1
print((count*100)/len(actual))

100.0